name: test
on:
  push:
    branches:
      - '*'
      - '!*WIP'
      - '!*-tests'
jobs:
  linux-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./run_tests.sh -l
