name: test
on:
  push:
    branches:
      - '*'
      - '!*WIP'
jobs:
  macos-compilation:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: make leak_test
  linux-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make leak_test
